-- Translate existing labels and enforce the same Estonian taxonomy used by the app.
begin;

with translations(old_topic, new_topic) as (values
  ('academic writing', 'akadeemiline kirjutamine'),
  ('commercialisation', 'teadustulemuste kommertsialiseerimine'),
  ('developer technology', 'arendustehnoloogiad'),
  ('digital humanities', 'digihumanitaaria'),
  ('doctoral research', 'doktoriõpe'),
  ('doctoral researchers', 'doktoriõpe'),
  ('elevator pitch', 'liftikõne'),
  ('hands-on learning', 'praktiline õpe'),
  ('intellectual property', 'intellektuaalomand'),
  ('knowledge transfer', 'teadmussiire'),
  ('open access', 'avatud juurdepääs'),
  ('open knowledge', 'avatud teadmus'),
  ('open publishing', 'avatud kirjastamine'),
  ('public speaking', 'avalik esinemine'),
  ('publishing', 'kirjastamine'),
  ('research collaboration', 'teaduskoostöö'),
  ('research communication', 'teaduskommunikatsioon'),
  ('research data management', 'teadusandmete haldamine'),
  ('research impact', 'teaduse mõju'),
  ('research policy', 'teaduspoliitika'),
  ('software development', 'tarkvaraarendus'),
  ('surveillance studies', 'jälgimisuuringud'),
  ('thesis presentations', 'lõputöö esitlemine'),
  ('artificial intelligence', 'tehisintellekt'),
  ('digital sovereignty', 'digitaalne suveräänsus'),
  ('urban studies', 'linnauuringud'),
  ('sustainability', 'kestlikkus'),
  ('research methods', 'uurimismeetodid'),
  ('reproducibility', 'reprodutseeritavus'),
  ('public policy', 'avalik poliitika'),
  ('governance', 'valitsemine'),
  ('education', 'haridus'),
  ('social sciences', 'sotsiaalteadused'),
  ('society', 'ühiskond'),
  ('technology', 'tehnoloogia'),
  ('policy', 'poliitika')
)
update public.items i
set topics = array(
  select distinct coalesce(t.new_topic, lower(trim(original.topic)))
  from unnest(i.topics) as original(topic)
  left join translations t on t.old_topic = lower(trim(original.topic))
  order by 1
);

alter table public.items add constraint items_topics_estonian
check (topics <@ array[
  'ajakirjandus',
  'ajalugu',
  'akadeemiline kirjutamine',
  'andmeteadus',
  'antropoloogia',
  'arendustehnoloogiad',
  'avalik esinemine',
  'avalik poliitika',
  'avatud juurdepääs',
  'avatud kirjastamine',
  'avatud teadmus',
  'avatud teadus',
  'bioloogia',
  'digihumanitaaria',
  'digitaalne suveräänsus',
  'digitaalne ühiskond',
  'doktoriõpe',
  'ebavõrdsus',
  'eetika',
  'ettevõtlus',
  'filosoofia',
  'füüsika',
  'haridus',
  'infokorraldus',
  'infoteadus',
  'inseneriteadused',
  'intellektuaalomand',
  'jälgimisuuringud',
  'keeleteadus',
  'keemia',
  'keskkond',
  'kestlikkus',
  'kirjandusteadus',
  'kirjastamine',
  'kliimamuutused',
  'kommunikatsioon',
  'kultuuriuuringud',
  'kunst',
  'kõrgharidus',
  'liftikõne',
  'linnauuringud',
  'loodusteadused',
  'lõputöö esitlemine',
  'majandus',
  'matemaatika',
  'meditsiin',
  'meediauuringud',
  'poliitika',
  'politoloogia',
  'praktiline õpe',
  'psühholoogia',
  'rahvusvahelised suhted',
  'reprodutseeritavus',
  'ränne',
  'soouuringud',
  'sotsiaalteadused',
  'sotsiaaltöö',
  'sotsioloogia',
  'tarkvaraarendus',
  'teadmussiire',
  'teadusandmete haldamine',
  'teaduse mõju',
  'teaduskommunikatsioon',
  'teaduskoostöö',
  'teaduskorraldus',
  'teaduspoliitika',
  'teadustulemuste kommertsialiseerimine',
  'tehisintellekt',
  'tehnoloogia',
  'tervis',
  'turvalisus',
  'uurimismeetodid',
  'valitsemine',
  'õigusteadus',
  'ühiskond'
]::text[]);

commit;
